### ISSUE TITLE
Make Experiment Builder

### ISSUE THREAD

**Issue by Maartenvm** [eWaterCycle/JupyterLab-Experiment-Builder#1]
Set up our own JupyterLab instance for the exeriment builder, import the data from the globe visualization into the first block of python code, provide provenance data / interface. 

- [ ] #14 Set up our own JupyterLab
- [ ] #15 Import data from globe visualization.
- [ ] #16 Display provenance data
- [ ] #19 Export experiment button
- [ ] #17 Save experiment button
- [ ] #20 Share experiment button
